/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PreviewRouteImport } from "./routes/preview"
import { Route as LandingRouteImport } from "./routes/landing"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DocumentDocumentIdRouteImport } from "./routes/document.$documentId"

const PreviewRoute = PreviewRouteImport.update({
  id: "/preview",
  path: "/preview",
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: "/landing",
  path: "/landing",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentDocumentIdRoute = DocumentDocumentIdRouteImport.update({
  id: "/document/$documentId",
  path: "/document/$documentId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/landing": typeof LandingRoute
  "/preview": typeof PreviewRoute
  "/document/$documentId": typeof DocumentDocumentIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/landing": typeof LandingRoute
  "/preview": typeof PreviewRoute
  "/document/$documentId": typeof DocumentDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/landing": typeof LandingRoute
  "/preview": typeof PreviewRoute
  "/document/$documentId": typeof DocumentDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/landing" | "/preview" | "/document/$documentId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/landing" | "/preview" | "/document/$documentId"
  id: "__root__" | "/" | "/landing" | "/preview" | "/document/$documentId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  PreviewRoute: typeof PreviewRoute
  DocumentDocumentIdRoute: typeof DocumentDocumentIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/preview": {
      id: "/preview"
      path: "/preview"
      fullPath: "/preview"
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/landing": {
      id: "/landing"
      path: "/landing"
      fullPath: "/landing"
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/document/$documentId": {
      id: "/document/$documentId"
      path: "/document/$documentId"
      fullPath: "/document/$documentId"
      preLoaderRoute: typeof DocumentDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  PreviewRoute: PreviewRoute,
  DocumentDocumentIdRoute: DocumentDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
